baseurl: "/prezentace"
tabzillaurl: "https://www.mozilla.cz/"

title: "Mozilla.cz - prezentace"
language: "cs"

permalink: pretty

include: ["_common"]

exclude:
 - [vendor]
 - Gemfile
 - Gemfile.lock

